---
server:
  port: 8778
  
spring:
  profiles: dev
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://10.1.233.16:3336/seeddb?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 2
      max-lifetime: 180000
  jpa:
    show-sql: true

service-config:
  url:
    swagger-host:
